### ISSUE TITLE
Sound played two times regardless of preferences

### ISSUE THREAD

**Issue by raffaem** [blackjackshellac/kitchenTimer#52] opened 2021-03-08 09:02 UTC
In preferences->sound->"play sound" I put "1", but the sound is played 2 times regardless.

Did I misinterpret this option?

**Comment by blackjackshellac** [comment] 2021-03-08 11:12
Yes, you interpreted the option correctly, no it doesn't work as intended when set to one.

Are you using the github or the release version?

**Comment by raffaem** [comment] 2021-03-08 11:18
I am using the release version

**Comment by blackjackshellac** [comment] 2021-03-08 19:41
This is now fixed on github.

**Closed by blackjackshellac** 2021-03-08 19:41 UTC
Labels: bug

**Comment by blackjackshellac** [comment] 2021-03-10 13:38
BTW @raffaem, fix is now updated at gnome.extensions.org

**Comment by raffaem** [comment] 2021-03-10 13:47
Thanks! 🤠

**Comment by raffaem** [comment] 2021-03-10 13:49
I don't see updates on extensions.gnome.org

I have version 17

**Comment by blackjackshellac** [comment] 2021-03-10 14:07
That's the version with the fix.
