### ISSUE TITLE
If possible, please support GNOME 3.36

### ISSUE THREAD

**Issue by eugene-rom** [blackjackshellac/kitchenTimer#35] opened 2021-01-20 07:41 UTC
While version 8 of this extension works in 3.36, version 10 is not. 

It says in log:
`Jan 20 09:31:26 eugene gnome-shell[1214]: JS ERROR: Extension kitchentimer@blackjackshellac.ca: SyntaxError: invalid regexp group @ /home/eugene/.local/share/gnome-shell/extensions/kitchentimer@blackjackshellac.ca/alarm_timer.js:1
`

Settings dialog also not displayed.

I think, support for gnome 3.36 is good idea, as quite popular Ubuntu 20.04 LTS uses gnome 3.36.
Thank you.

**Comment by blackjackshellac** [comment] 2021-01-20 11:32
And I was so happy to finally see named capture groups in javascript. I'll look into it today.

**Comment by eugene-rom** [comment] 2021-01-20 12:03
Thank you!

Correction for my post - v8 also doesn't work in 3.36, (`Jan 20 13:57:46 eugene gjs[2135]: JS WARNING: [/home/eugene/.local/share/gnome-shell/extensions/kitchentimer@blackjackshellac.ca/prefs.js 104]: reference to undefined property "id"`).

v7 works ok.

**Comment by blackjackshellac** [comment] 2021-01-20 13:51
Settings hsould work in 20.04 now

42369d15648b03ecd2033accc939af268b9a618e

**Comment by blackjackshellac** [comment] 2021-01-20 13:55
Verified that the problem is named regex groups,

```
gjs> re=/(?<foo>[a-z]+)/;
typein:1:1 invalid regexp group:
typein:1:1 (?<foo>[a-z]+)
typein:1:1 .^
  @<stdin>:1:42
```

**Comment by blackjackshellac** [comment] 2021-01-20 16:15
@eugene-rom can you try with the latest master branch from github?

**Comment by eugene-rom** [comment] 2021-01-20 17:15
@blackjackshellac, tried, and it's fully working! Thank you!

**Comment by blackjackshellac** [comment] 2021-01-20 19:15
Mostly working, I'll test a bit more and then submit an update to extensions.gnome.org.  I'm going to close this now.

**Closed by blackjackshellac** 2021-01-20 19:15 UTC
Labels: enhancement
